# Generated by Django 5.0.4 on 2024-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('pub_date', models.DateTimeField(verbose_name='작성일')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('agency', models.CharField(max_length=20, verbose_name='처리기관')),
                ('status', models.CharField(max_length=20, null=True, verbose_name='추진상황')),
                ('rating', models.IntegerField(verbose_name='동의수')),
                ('category', models.CharField(max_length=20, verbose_name='분야')),
            ],
        ),
        migrations.CreateModel(
            name='CW24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('agency', models.CharField(max_length=10, verbose_name='처리기관')),
                ('pub_date', models.DateTimeField(verbose_name='작성일')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('status', models.CharField(max_length=20, null=True, verbose_name='추진상황')),
                ('views', models.IntegerField(null=True, verbose_name='조회수')),
                ('content', models.CharField(max_length=300, null=True, verbose_name='내용')),
                ('comment_num', models.IntegerField(null=True, verbose_name='댓글수')),
                ('result', models.CharField(max_length=300, null=True, verbose_name='처리결과')),
            ],
        ),
        migrations.CreateModel(
            name='Epeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('agency', models.CharField(max_length=10, verbose_name='처리기관')),
                ('pub_date', models.DateTimeField(verbose_name='작성일')),
                ('status', models.CharField(max_length=10, verbose_name='추진상황')),
                ('views', models.IntegerField(verbose_name='조회수')),
                ('rating', models.FloatField(verbose_name='평점')),
                ('field', models.CharField(max_length=50, verbose_name='분야')),
                ('content', models.CharField(max_length=300, verbose_name='내용')),
            ],
        ),
        migrations.CreateModel(
            name='Ideaseoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('pub_date', models.DateTimeField(verbose_name='작성일')),
                ('period', models.CharField(max_length=50, verbose_name='기간')),
                ('status', models.CharField(max_length=10, verbose_name='추진상황')),
                ('views', models.IntegerField(verbose_name='조회수')),
                ('field', models.CharField(max_length=50, verbose_name='분야')),
                ('content', models.CharField(max_length=300, verbose_name='내용')),
            ],
        ),
    ]
