# Generated by Django 4.2.6 on 2024-04-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualize", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ideaseoul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("url", models.CharField(max_length=100, verbose_name="URL")),
                ("pub_date", models.DateTimeField(verbose_name="작성일")),
                ("period", models.CharField(max_length=50, verbose_name="기간")),
                ("status", models.CharField(max_length=10, verbose_name="추진상황")),
                ("views", models.IntegerField(verbose_name="조회수")),
                ("field", models.CharField(max_length=50, verbose_name="분야")),
                ("content", models.CharField(max_length=300, verbose_name="내용")),
            ],
        ),
    ]
