# Generated by Django 5.0.4 on 2024-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('pub_date', models.DateTimeField(verbose_name='작성일')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('agency', models.CharField(max_length=20, verbose_name='처리기관')),
                ('status', models.CharField(max_length=20, null=True, verbose_name='추진상황')),
                ('rating', models.IntegerField(verbose_name='동의수')),
                ('category', models.CharField(max_length=20, verbose_name='분야')),
            ],
        ),
    ]
