# Generated by Django 4.2.6 on 2024-04-17 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visualize", "0002_congress"),
        ("visualize", "0002_ideaseoul"),
    ]

    operations = []
