# Generated by Django 4.2.6 on 2024-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualize", "0003_merge_0002_congress_0002_ideaseoul"),
    ]

    operations = [
        migrations.CreateModel(
            name="CW24",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("url", models.CharField(max_length=200, verbose_name="URL")),
                ("agency", models.CharField(max_length=10, verbose_name="처리기관")),
                ("pub_date", models.DateTimeField(verbose_name="작성일")),
                ("start_date", models.DateTimeField(verbose_name="시작일")),
                ("end_date", models.DateTimeField(verbose_name="종료일")),
                (
                    "status",
                    models.CharField(max_length=20, null=True, verbose_name="추진상황"),
                ),
                ("views", models.IntegerField(null=True, verbose_name="조회수")),
                (
                    "content",
                    models.CharField(max_length=300, null=True, verbose_name="내용"),
                ),
                ("comment_num", models.IntegerField(null=True, verbose_name="댓글수")),
                (
                    "result",
                    models.CharField(max_length=300, null=True, verbose_name="처리결과"),
                ),
            ],
        ),
    ]
